Temporarily disable Windows CI due to error C1001 with MSVC 19.27.29111.0
This is most likely a compiler bug. Workaround or solution to be
investigated.